# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('alias', models.CharField(db_index=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('alias', models.CharField(db_index=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('host', models.GenericIPAddressField()),
                ('version', models.CharField(default=b'no_version', max_length=100)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_api.Env')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_name', to='info_api.Item')),
            ],
            options={
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('alias', models.CharField(db_index=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('mission', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('svn_url', models.URLField()),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_api.Env')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_name', to='info_api.Item')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='list',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_api.Location'),
        ),
    ]
